services:
  - type: web
    name: Hotel-Django
    env: python
    rootDir: django/hotel_furavery  
    buildCommand: "pip install -r requirements.txt"
    preDeployCommand: "python manage.py migrate"
    startCommand: "python manage.py runserver"

